### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by sukemaru-injp** [sukemaru-injp/furima-34521#9]
#url
https://furima-34521.herokuapp.com/

#Basic認証
id: adimn
pin: 2222

#出品者
mail: a@test
pin: aaaaaa1

#購入者
mail: s@test
pin: ssssss1

**Comment by sukemaru-injp** [comment]
dbリセットを忘れていたので、リセットして同じmailとpinで作り直しました

**Comment by takumi0530** [comment]
@sukemaru-injp さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/76197191/109463175-eaa8f300-7aa7-11eb-9775-ef5f25c61641.png)
